name: ci

on:
  push:
    branches: [ main ]
  pull_request:

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  build-and-healthcheck:
    runs-on: ubuntu-latest
    permissions:
      contents: read
    env:
      DOCKER_BUILDKIT: 1
      COMPOSE_DOCKER_CLI_BUILD: 1
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Prepare env
        run: cp .env.example .env

      - name: Build & start stack
        run: docker compose up -d --build

      - name: Wait for API health via edge
        run: |
          set -e
          for i in {1..60}; do
            if curl -fsS http://localhost:8080/api/health >/dev/null; then
              echo "edge/api healthy"; exit 0;
            fi
            echo "waiting ($i/60)…"
            sleep 2
          done
          echo "healthcheck failed"
          exit 1

      - name: Dump compose status & logs (on failure)
        if: failure()
        run: |
          docker compose ps
          docker compose logs --no-color > compose-logs.txt

      - name: Upload logs artifact (on failure)
        if: failure()
        uses: actions/upload-artifact@v4
        with:
          name: compose-logs
          path: compose-logs.txt

      - name: Tear down
        if: always()
        run: docker compose down -v